redir-port: 7892
tproxy-port: 7894
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
tcp-concurrent: true
unified-delay: true
keep-alive-interval: 15
keep-alive-idle: 600
disable-keep-alive: false
external-controller: "0.0.0.0:9090"
secret: one
bind-address: "0.0.0.0"
external-ui: "ui"
enable-process: true
find-process-mode: always
ipv6: false
tun:
  enable: true
  device: Meta
  stack: system
  mtu: 1500
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: true
  dns-hijack:
    - tcp://any:53
    - udp://any:53
dns:
  enable: true
  cache-algorithm: arc
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  respect-rules: true
  nameserver:
    - "8.8.8.8" #"https://dns.google/dns-query"
    - "1.1.1.1" #"https://dns.cloudflare.com/dns-query"
  proxy-server-nameserver:
    - "112.215.198.248"
    - "112.215.198.254"
  default-nameserver:
    - "8.8.8.8"
    - "1.1.1.1"
profile:
  store-selected: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      port:
        - "80"
        - "8080"
      override-destination: true
    TLS:
      port:
        - "443"
        - "8443"
      override-destination: true
    QUIC:
      port:
        - "443"
        - "8443"
      override-destination: true
rule-providers:
  R_ads_all:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"
    path: "./rule_provider/block_ads_all.mrs"
    interval: 86400
  R_nsfw:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs"
    path: "./rule_provider/block_porn.mrs"
    interval: 86400
  R_whatsapp:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/whatsapp.mrs"
    path: "./rule_provider/whatsapp.mrs"
    interval: 86400
  R_youtube:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
    path: "./rule_provider/youtube.mrs"
    interval: 86400
proxy-providers:
  Proxy:
    type: file
    path: "./proxy_provider/akun.yaml"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: SELECT
    type: select
    disable-udp: false
    use:
      - Proxy
  - name: FALLBACK
    type: fallback
    disable-udp: false
    use:
      - Proxy
    url: https://www.gstatic.com/generate_204
    interval: 120
  - name: URLTEST
    type: urltest
    disable-udp: false
    use:
      - Proxy
    url: https://www.gstatic.com/generate_204
    interval: 120
  - name: WHATSAPP
    type: select
    disable-udp: false
    proxies:
      - FALLBACK
      - SELECT
rules:
  - AND,((NETWORK,udp),(AND,((RULE-SET,R_youtube),(DST-PORT,443)))),REJECT-DROP
  - RULE-SET,R_whatsapp,WHATSAPP
  - RULE-SET,R_ads_all,REJECT-DROP
  - RULE-SET,R_nsfw,REJECT-DROP
  - MATCH,GLOBAL
