#!/bin/bash
#
# Copyright (C) 2024 nosignal

neko_dir="/etc/neko"
tmp_dir="/tmp"

echo "[ `date +%T` ] - Checking Files..."

# ---- Stop Neko jika jalan ----
if [ -x "$neko_dir/core/neko" ]; then
    echo "[ `date +%T` ] - Stopping Neko..."
    "$neko_dir/core/neko" -k 2>/dev/null
fi
if [ -x "$neko_dir/core/singbox" ]; then
    echo "[ `date +%T` ] - Stopping Singbox..."
    "$neko_dir/core/singbox" -k 2>/dev/null
fi

# ---- Restore atau cek file ----
files_check() {
    uci set uhttpd.main.index_page='index.php'
    uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
    uci commit uhttpd

    /etc/init.d/uhttpd restart
}

if [ -f "/tmp/neko/neko.bak" ]; then
    echo "[ `date +%T` ] - Old Configs Detected. Restoring..."
    
    [ -f "/tmp/neko/cache.db" ] && cp -rf "/tmp/neko/cache.db" "/etc/neko/cache.db"
    cp -rf /tmp/neko/config/* "/etc/neko/config/"
    cp -rf /tmp/neko/proxy_provider/* "/etc/neko/proxy_provider/"
    cp -rf /tmp/neko/rule_provider/* "/etc/neko/rule_provider/"
else
    echo "[ `date +%T` ] - No Old Files. Checking Files..."
    files_check
fi

# ---- Pastikan Neko tetap disabled setelah install ----
uci set neko.cfg.enabled='0'
uci commit neko
