#!/bin/sh
# Neko FW4 Reload

TUN_DEV="Meta"
RULE_NAME="neko_tun"

start() {
    echo "[`date +%T`] - Adding Neko firewall rule"

    uci -q delete firewall.$RULE_NAME
    uci set firewall.$RULE_NAME="rule"
    uci set firewall.$RULE_NAME.name="Neko TUN"
    uci set firewall.$RULE_NAME.device="$TUN_DEV"
    uci set firewall.$RULE_NAME.proto="tcp udp"
    uci set firewall.$RULE_NAME.target="ACCEPT"

    uci commit firewall
    fw4 reload
}

stop() {
    echo "[`date +%T`] - Removing Neko firewall rule"

    uci -q delete firewall.$RULE_NAME
    uci commit firewall
    fw4 reload
}

[ "$1" = "stop" ] && stop || start
