#!/bin/bash
# Neko TUN Script - FW4 Only
# MIT License

tun_device="Meta"
nft=$(command -v nft)

start_tun() {
    echo "[`date +%T`] - Activating TUN device ${tun_device}"

    # Hapus rule lama
    for chain in forward input srcnat; do
        handles=$(nft -a list chain inet fw4 $chain | grep -E "Neko" | awk -F '# handle ' '{print $2}')
        for h in $handles; do
            $nft delete rule inet fw4 $chain handle $h
        done
    done

    # Tambahkan rule
    $nft insert rule inet fw4 forward position 0 meta l4proto { tcp, udp } oifname $tun_device counter accept comment "Neko TUN Forward"
    $nft insert rule inet fw4 forward position 0 meta l4proto { tcp, udp } iifname $tun_device counter accept comment "Neko TUN Forward"
    $nft insert rule inet fw4 input position 0 meta l4proto { tcp, udp } iifname $tun_device counter accept comment "Neko TUN Input"
    $nft insert rule inet fw4 srcnat position 0 meta nfproto { ipv4 } oifname $tun_device counter return comment "Neko TUN Postrouting"

    echo "[`date +%T`] - TUN ${tun_device} activated"
}

stop_tun() {
    echo "[`date +%T`] - Cleaning TUN device ${tun_device}"
    for chain in forward input srcnat; do
        handles=$(nft -a list chain inet fw4 $chain | grep -E "Neko" | awk -F '# handle ' '{print $2}')
        for h in $handles; do
            $nft delete rule inet fw4 $chain handle $h
        done
    done
    echo "[`date +%T`] - TUN ${tun_device} cleaned"
}

# Default: start TUN, gunakan "stop" sebagai argumen untuk mematikan
if [[ "$1" == "stop" ]]; then
    stop_tun
else
    start_tun
fi
