#
# Copyright (C) 2024 nosignals
#
name: Building Mihomo & Sing-box Kernel DEV

on:
  workflow_dispatch:
    inputs:
      mihomo_version:
        description: 'Mihomo version'
        required: true
        default: '1.19.20'
        type: string
      singbox_version:
        description: 'Sing-box version'
        required: true
        default: '1.12.21'
        type: string

jobs:
  build_ipk:
    permissions:
      contents: write
    name: Build Neko
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 24.10.5
          - 25.12.0
        arch:
          - x86_64
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          - arm_cortex-a9

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Preparing Neko
        run: |
          echo ""
          mkdir feeds artifacts
          cp -rf ./mihomo ./feeds
          cp -rf ./sing-box ./feeds

      - name: Building Kernel Packages
        uses: nosignals/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: mihomo sing-box
          NO_SHFMT_CHECK: 1

      - name: Rename Packages with Arch Suffix
        run: |
          cd ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/
          for f in mihomo* sing-box*; do
            [ -f "$f" ] || continue
            ext="${f##*.}"
            base="${f%.*}"
            mv "$f" "${base}_${{ matrix.arch }}.${ext}"
          done

      - name: Upload to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/*
          overwrite: true
          tag: core_${{ inputs.mihomo_version }}_${{ inputs.singbox_version }}
          prerelease: true
          file_glob: true
          body: |
            # NEKO CORE PACKAGES
            ### Mihomo Kernel ${{ inputs.mihomo_version }}
            - Changelog : [v${{ inputs.mihomo_version }}](https://github.com/MetaCubeX/mihomo/releases/tag/v${{ inputs.mihomo_version }})
            - Wiki : [wiki.metacubex.one](https://wiki.metacubex.one)

            ### Sing-box Kernel ${{ inputs.singbox_version }}
            - Changelog : [v${{ inputs.singbox_version }}](https://github.com/SagerNet/sing-box/releases/tag/v${{ inputs.singbox_version }})
            - Wiki : [sing-box.sagernet.org](https://sing-box.sagernet.org)

            ### Dependency Requirement
            - ` ca-bundle, ip-full, kmod-tun `
            
