name: Build Neko Next (Snapshot / 25.12 - APK)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.arch }} - snapshot
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - armsr-armv8
          - x86-64

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Custom Feed
        run: |
          mkdir -p custom-feeds/neko
          cp -rf ./luci-app-neko custom-feeds/neko/

      - name: Build Package (Snapshot SDK - APK)
        uses: openwrt/gh-action-sdk@v7
        env:
          ARCH: ${{ matrix.arch }}-snapshot
          FEEDNAME: neko
          FEEDDIR: ${{ github.workspace }}/custom-feeds
          PACKAGES: luci-app-neko
          V: s

      - name: Collect APK Artifacts
        run: |
          mkdir -p release
          find bin/ -type f -name "*.apk" -exec cp {} release/ \;

          if [ ! -f release/*.apk ]; then
            echo "No APK generated!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: neko-${{ matrix.arch }}
          path: release/*.apk
          if-no-files-found: error

  release:
    name: Create Snapshot Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show Files
        run: ls -R artifacts

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/**/*.apk
          tag: snapshot-${{ github.run_number }}
          file_glob: true
          overwrite: true
          
